import "./globals.css";
import MainLayout from "./components/MainLayout/MainLayout";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/context/ThemeContext";
import { ReduxProvider } from "@/redux/provider";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eteration Case App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ThemeProvider>
            <MainLayout>{children}</MainLayout>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
